name: ChessLibs
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - --extra-index-url  https://download.pytorch.org/whl/cu117
    - torch==2.1.0
    - torchaudio
    - torchvision
