[package]
name = "Bindings"
version = "0.1.0"
edition = "2021"

#[workspace]

[lib]
name = "Bindings"
crate-type = ["cdylib"]

[dependencies]
masks = {path = "../masks"}
magic = {path = "../magic"}
GameState = {path = "../GameState"}
pyo3 = { version = "0.20.0", features = ["extension-module"] }
