[package]
name = "engine"
version = "0.1.0"
publish = false
edition = "2021"

clap = { version = "4.0", features = ["derive"] }

[[bin]]
path = "src/main.rs"
name = "ChessEngine"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
regex = "1.10.6"
